name: Update RSS

on:
  schedule:
    - cron: "7 */3 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Get main branch
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install feedparser feedgen

      - name: Generate feed
        run: |
          python generate_feed.py

      # Checkout gh-pages to a separate directory
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Update feed.xml
        run: |
          cp docs/feed.xml gh-pages/feed.xml

      - name: Commit and push
        run: |
          cd gh-pages

          git config user.name github-actions
          git config user.email github-actions@github.com

          git add feed.xml

          git diff --cached --quiet && exit 0

          git commit -m "Update RSS feed"
          git push